spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: capitole
    password: capitole
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true


